baseURL: "https://niusj03.github.io/blog"
languageCode: en-us
title: Shengjie's Blog
theme: "PaperMod"


params:
  # home-info mode
  homeInfoParams:
    Title: "Hello everyone, welcome to my blog"
    Content: "In both theoretical studies and practical projects, I often face recurring challenges. However, I always fail to find immediate solutions, leading me to consistently search for answers.
    Occasionally, unforeseen errors arise. I've found that this can be quite time-consuming and draining. That's why I've created this blog, documenting my learning notes and experimental guides.
    
    \n\n~
    
    \nMany thinks for visiting, and wish you find something valuable here."

  socialIcons:
    - name: Rss
      url: "index.xml"
    - name: github
      url: "https://github.com/niusj03"




  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true



menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: mathtex
      name: MathTex
      url: chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.math.uci.edu/~xiangwen/pdf/LaTeX-Math-Symbols.pdf
      weight: 40
    - identifier: example
      name: emojisearch
      url: https://www.emojisearch.app/
      weight: 50